apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maine-mlops-infra
  namespace: argocd
spec:
  project: mlops-infrastructure
  source:
    repoURL: 'https://github.com/MosesDastmard/maine-mlops-infra.git'
    targetRevision: HEAD
    path: manifests # The folder where your k8s files are
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true