# Kustomization for Feast Feature Store
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-feast

resources:
  - namespace.yml
  - configmap.yml
  - postgresql.yml
  - redis.yml
  - feature-server.yml
  - ui.yml
