# Kustomization for services-stream
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-stream

resources:
  - namespace.yml
  - producer.yml
  - raw-consumer.yaml
  - daily-consumer.yaml
  - weekly-consumer.yaml
