# Kustomization for services-stream
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-stream

resources:
  - namespace.yml
  - flink-checkpoints-pvc.yaml
  - producer.yml
  - trans-consumer.yaml
